version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the React Vite application...
      - npm run build
  post_build:
    commands:
      - echo Build completed.
      - echo Preparing to deploy...

artifacts:
  files:
    - "**/*"
  base-directory: "build"
